version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    image: skygvinn/debian-ruby-nodejs:v2.5.3
    container_name: restaurant
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
    volumes:
      - .:/var/www/restaurant:Z
    working_dir: /var/www/restaurant
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
